FROM alpine:3.22 AS certificates
RUN apk add --no-cache ca-certificates

FROM scratch
ARG DYNO_VERSION=dev
ARG DYNO_COMMIT=unknown
LABEL org.opencontainers.image.title="dyno site" \
      org.opencontainers.image.version="${DYNO_VERSION}" \
      org.opencontainers.image.revision="${DYNO_COMMIT}"

COPY --from=certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY dyno /dyno
COPY site/ /site/
COPY root/ /

USER 65532:65532
EXPOSE 8080
ENTRYPOINT ["/dyno"]
CMD ["--site", "/site", "--port", "8080"]
